[package]
name = "crystal"
version = "0.0.0"
authors = ["Jacob Humphrey <jacob.ryan.humphrey@gmail.com>"]
publish = false

[dependencies]
getopts = "0"
libc = "0"
glob = "0"
env_logger = "0"
log = "0"
# time = "0.1"
