[package]
name = "crystal"
version = "0.0.0"
authors = ["Jacob Humphrey <jacob.ryan.humphrey@gmail.com>"]
publish = false

[dependencies]
getopts = "0.2"
libc = "0.2"
glob = "0.2.11"
env_logger = "0.4.3"
log = "0.4.1"
time = "0.1"
